/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutStrategiesRouteImport } from './routes/_layout/strategies'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutScannerRouteImport } from './routes/_layout/scanner'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutExplorerRouteImport } from './routes/_layout/explorer'
import { Route as LayoutBrokersRouteImport } from './routes/_layout/brokers'
import { Route as LayoutBacktestRouteImport } from './routes/_layout/backtest'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStrategiesRoute = LayoutStrategiesRouteImport.update({
  id: '/strategies',
  path: '/strategies',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutScannerRoute = LayoutScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExplorerRoute = LayoutExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBrokersRoute = LayoutBrokersRouteImport.update({
  id: '/brokers',
  path: '/brokers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBacktestRoute = LayoutBacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/backtest': typeof LayoutBacktestRoute
  '/brokers': typeof LayoutBrokersRoute
  '/explorer': typeof LayoutExplorerRoute
  '/items': typeof LayoutItemsRoute
  '/scanner': typeof LayoutScannerRoute
  '/settings': typeof LayoutSettingsRoute
  '/strategies': typeof LayoutStrategiesRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/backtest': typeof LayoutBacktestRoute
  '/brokers': typeof LayoutBrokersRoute
  '/explorer': typeof LayoutExplorerRoute
  '/items': typeof LayoutItemsRoute
  '/scanner': typeof LayoutScannerRoute
  '/settings': typeof LayoutSettingsRoute
  '/strategies': typeof LayoutStrategiesRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/backtest': typeof LayoutBacktestRoute
  '/_layout/brokers': typeof LayoutBrokersRoute
  '/_layout/explorer': typeof LayoutExplorerRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/scanner': typeof LayoutScannerRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/strategies': typeof LayoutStrategiesRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/backtest'
    | '/brokers'
    | '/explorer'
    | '/items'
    | '/scanner'
    | '/settings'
    | '/strategies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/backtest'
    | '/brokers'
    | '/explorer'
    | '/items'
    | '/scanner'
    | '/settings'
    | '/strategies'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/backtest'
    | '/_layout/brokers'
    | '/_layout/explorer'
    | '/_layout/items'
    | '/_layout/scanner'
    | '/_layout/settings'
    | '/_layout/strategies'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/strategies': {
      id: '/_layout/strategies'
      path: '/strategies'
      fullPath: '/strategies'
      preLoaderRoute: typeof LayoutStrategiesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/scanner': {
      id: '/_layout/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof LayoutScannerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/explorer': {
      id: '/_layout/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof LayoutExplorerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/brokers': {
      id: '/_layout/brokers'
      path: '/brokers'
      fullPath: '/brokers'
      preLoaderRoute: typeof LayoutBrokersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/backtest': {
      id: '/_layout/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof LayoutBacktestRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutBacktestRoute: typeof LayoutBacktestRoute
  LayoutBrokersRoute: typeof LayoutBrokersRoute
  LayoutExplorerRoute: typeof LayoutExplorerRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutScannerRoute: typeof LayoutScannerRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStrategiesRoute: typeof LayoutStrategiesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutBacktestRoute: LayoutBacktestRoute,
  LayoutBrokersRoute: LayoutBrokersRoute,
  LayoutExplorerRoute: LayoutExplorerRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutScannerRoute: LayoutScannerRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStrategiesRoute: LayoutStrategiesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
